Pre-commit Action Test (#9)
* Pre-commit Action Test

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Fix for new files

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Fix

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Fix

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Adding toml file

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Test

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Move autofix to action

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Update

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Update

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* [pre-commit.ci] Fixing issues with pre-commit

* Test

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* TEst

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Maybe

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Test

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Test

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* [pre-commit.ci] Fixing issues with pre-commit

* Break

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* [pre-commit.ci] Fixing issues with pre-commit

* Break

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* name

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* name

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* copied  file

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* name

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* name

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* rename

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* try someone else's script

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* fix

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Fix

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Fix

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* fix

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* let's see

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* [pre-commit.ci lite] apply automatic fixes

* update

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* Add pre-commit action

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

* [pre-commit.ci lite] apply automatic fixes

---------

Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: pre-commit-ci-lite[bot] <117423508+pre-commit-ci-lite[bot]@users.noreply.github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -37,13 +37,18 @@ jobs:
         git diff --name-only HEAD^..HEAD ':!docs' | while read i
         do
           echo "Checking for changes: $i"
-          git show HEAD^:$i > /tmp/check_changes/$(basename $i)
-          if ! python ./compare_sources.py $i /tmp/check_changes/$(basename $i)
+          if ! git show HEAD^:$i > /tmp/check_changes/$(basename $i)
+          then
+            echo "New file found, or 'git show' failed, running tests."
+          elif ! python ./compare_sources.py $i /tmp/check_changes/$(basename $i)
           then
             echo "Change found, running tests."
-            echo "skip=0" >> $GITHUB_OUTPUT
-            break
+          else
+            continue
           fi
+
+          echo "skip=0" >> $GITHUB_OUTPUT
+          break
         done
     - name: Install dependencies
       shell: bash
